// Маппинг режимов готовки на иконки MDI
// Соответствует program_names интеграции skycooker-ha (RU/EN)

const MODE_ICONS: Record<string, string> = {
  // RU
  мультиповар: 'mdi:pot-mix',
  'рис/крупы': 'mdi:rice',
  томление: 'mdi:pot-steam',
  плов: 'mdi:rice',
  жарка: 'mdi:frying-pan',
  тушение: 'mdi:pot-steam',
  'паста/макароны': 'mdi:pasta',
  'молочная каша': 'mdi:bowl-mix',
  суп: 'mdi:soup',
  йогурт: 'mdi:cup',
  выпечка: 'mdi:bread-slice',
  'на пару': 'mdi:steam',
  'варка/бобовые': 'mdi:pot',
  дичь: 'mdi:food-drumstick',
  пицца: 'mdi:pizza',
  хлеб: 'mdi:bread-slice',
  'детское питание': 'mdi:baby-bottle',
  вакуум: 'mdi:vacuum',
  фритюр: 'mdi:frying-pan',
  десерты: 'mdi:cake',
  экспресс: 'mdi:lightning-bolt',
  холодец: 'mdi:food',
  'йогурт/тесто': 'mdi:cup',
  'запеканка/чизкейк': 'mdi:cheese',
  соус: 'mdi:cup',
  разогрев: 'mdi:microwave',
  подогрев: 'mdi:heat-wave',
  варка: 'mdi:pot',
  'режим ожидания': 'mdi:power-sleep',
  нет: 'mdi:minus',
  // EN
  'multi-chef': 'mdi:pot-mix',
  'rice/cereals': 'mdi:rice',
  languor: 'mdi:pot-steam',
  pilaf: 'mdi:rice',
  frying: 'mdi:frying-pan',
  stewing: 'mdi:pot-steam',
  pasta: 'mdi:pasta',
  'milk porridge': 'mdi:bowl-mix',
  soup: 'mdi:soup',
  yogurt: 'mdi:cup',
  baking: 'mdi:bread-slice',
  steam: 'mdi:steam',
  'cooking/legumes': 'mdi:pot',
  wildfowl: 'mdi:food-drumstick',
  pizza: 'mdi:pizza',
  bread: 'mdi:bread-slice',
  'baby food': 'mdi:baby-bottle',
  'sous-vide': 'mdi:vacuum',
  'deep frying': 'mdi:frying-pan',
  desserts: 'mdi:cake',
  express: 'mdi:lightning-bolt',
  galantine: 'mdi:food',
  'yogurt/dough': 'mdi:cup',
  cheesecake: 'mdi:cheese',
  sous: 'mdi:cup',
  'warming up': 'mdi:microwave',
  warming: 'mdi:heat-wave',
  cooking: 'mdi:pot',
  'standby mode': 'mdi:power-sleep',
  none: 'mdi:minus',
  // Legacy / alternative
  гриль: 'mdi:grill',
  пароварка: 'mdi:steam',
  каша: 'mdi:bowl',
  'жарка на воздухе': 'mdi:air-filter',
  ферментация: 'mdi:leaf',
  пастеризация: 'mdi:thermometer-water',
  сушка: 'mdi:fan',
};

export function getModeIcon(modeName: string): string {
  if (!modeName || typeof modeName !== 'string') return 'mdi:stove';
  const key = modeName.toLowerCase().trim();
  return MODE_ICONS[key] ?? 'mdi:stove';
}
